user:
  email:
    maximum_length: 255
  name:
    maximum_length: 50
category:
  max_time:
    minimum: 0
question:
  minimum_answers: 4
  correct_answer_number: 1
exams:
  questions_per_exam: 30
  time_limit: 1
mailer:
  from: "admin@framgia.com"
