user:
  csv:
    fields: ["name", "email"]
    filename: "user-list.csv"
    type: "text/csv"
mailer:
  from: "admin@gmail.com"
default_admin:
  name: "Admin"
  email: "admin@framgia.com"
  password: "password"
gravatar_url: "https://secure.gravatar.com/avatar/"
question:
  minimum_answers: 4
